services:
  - type: web
    name: telegram-trading-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TG_BOT_TOKEN
        value: YOUR_TOKEN_HERE
      - key: GIGACHAT_CLIENT_ID
        value: YOUR_CLIENT_ID
      - key: GIGACHAT_CLIENT_SECRET
        value: YOUR_CLIENT_SECRET
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com
